language: c++

branches:
  only:
  - main

compiler:
  - g++

addons:
  homebrew:
    packages: 
    - boost
    update: false
  apt:
    packages:
    - boost
    update: false

env:
  - BUILD_PYTHON=ON
  - BUILD_PYTHON=OFF

os:
  - linux
  - osx

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build && cd build

script:
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=OFF
  - make -j4